/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * 社員情報管理API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/iotassss/gizzwork/employee/go"
)

func main() {
	log.Printf("Server started")

	EmployeeAPIService := api.NewEmployeeAPIService()
	EmployeeAPIController := api.NewEmployeeAPIController(EmployeeAPIService)

	router := api.NewRouter(EmployeeAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
