version: '3.8'
services:
  app1:
    build: app1
    ports:
      - "8001:80"
    volumes:
      - ./app1:/usr/src/app
    env_file:
      - app1/.env
    depends_on:
      - db1
    networks:
      - my-custom-network

  db1:
    image: mysql:5.7
    env_file:
      - app1/.env
    volumes:
      - db1-data:/var/lib/mysql
    networks:
      - my-custom-network

  app2:
    build: app2
    ports:
      - "8002:80"
    volumes:
      - ./app2:/usr/src/app
    env_file:
      - app2/.env
    depends_on:
      - db2
    networks:
      - my-custom-network

  db2:
    image: mysql:5.7
    env_file:
      - app2/.env
    volumes:
      - db2-data:/var/lib/mysql
    networks:
      - my-custom-network

volumes:
  db1-data:
  db2-data:

networks:
  my-custom-network:
    driver: bridge
