/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * 社員情報管理API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
)



// EmployeeAPIRouter defines the required methods for binding the api requests to a responses for the EmployeeAPI
// The EmployeeAPIRouter implementation should parse necessary information from the http request,
// pass the data to a EmployeeAPIServicer to perform the required actions, then write the service results to the http response.
type EmployeeAPIRouter interface { 
	CreateEmployee(http.ResponseWriter, *http.Request)
	DeleteEmployee(http.ResponseWriter, *http.Request)
	GetEmployeeById(http.ResponseWriter, *http.Request)
	ListEmployees(http.ResponseWriter, *http.Request)
	UpdateEmployee(http.ResponseWriter, *http.Request)
}


// EmployeeAPIServicer defines the api actions for the EmployeeAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type EmployeeAPIServicer interface { 
	CreateEmployee(context.Context, Employee) (ImplResponse, error)
	DeleteEmployee(context.Context, string) (ImplResponse, error)
	GetEmployeeById(context.Context, string) (ImplResponse, error)
	ListEmployees(context.Context) (ImplResponse, error)
	UpdateEmployee(context.Context, string, Employee) (ImplResponse, error)
}
