/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * 社員情報管理API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api




type Employee struct {

	EmployeeId string `json:"employee_id"`

	Email string `json:"email,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	Role string `json:"role,omitempty"`
}

// AssertEmployeeRequired checks if the required fields are not zero-ed
func AssertEmployeeRequired(obj Employee) error {
	elements := map[string]interface{}{
		"employee_id": obj.EmployeeId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEmployeeConstraints checks if the values respects the defined constraints
func AssertEmployeeConstraints(obj Employee) error {
	return nil
}
