/*
 * Gizzwork/console - OpenAPI 3.0
 *
 * 社員情報管理API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/iotassss/gizzwork/console/go"
)

func main() {
	log.Printf("Server started")

	UserAPIService := api.NewUserAPIService()
	UserAPIController := api.NewUserAPIController(UserAPIService)

	router := api.NewRouter(UserAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
